#!/bin/bash
bash < tester > output2.txt 2> basherror.txt
valgrind --suppressions=readline.supp ./minishell < tester | grep -v "Minishell>" > output.txt 2>minishellerror.txt
diff --color output.txt output2.txt
