dollar:
	gcc -g transform_dollar.c /home/shhuang/Desktop/mishell-fedmarti/var3.c /home/shhuang/Desktop/mishell-fedmarti/var.c -o command -L/home/shhuang/Desktop/mishell-fedmarti/libft -lft

command:
	gcc -g command_list_new.c /home/shhuang/Desktop/mishell-fedmarti/var3.c /home/shhuang/Desktop/mishell-fedmarti/var.c -o command -L/home/shhuang/Desktop/mishell-fedmarti/libft -lft

all:
	gcc -g transform_dollar.c command_list_new.c /home/shhuang/Desktop/mishell-fedmarti/var3.c /home/shhuang/Desktop/mishell-fedmarti/var.c -o command -L/home/shhuang/Desktop/mishell-fedmarti/libft -lft